name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 07 * * FRI"

jobs:
  build_wheels:
    name: Build for Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pip
        run: pip install --upgrade pip

      - name: Install Python packages
        run: pip install --upgrade build twine

      - name: Build wheels
        run: python -m build

      - name: Check PyPi description
        run: python -m twine check dist/*
